//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFZ.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFZ.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno zákazníka musí být vyplněno..
        /// </summary>
        public static string valCustomerNameRequired {
            get {
                return ResourceManager.GetString("valCustomerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazník musí být vyplněn..
        /// </summary>
        public static string valCustomerRequired {
            get {
                return ResourceManager.GetString("valCustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum dodávky musí byt vyplněno..
        /// </summary>
        public static string valDeliveryDateRequired {
            get {
                return ResourceManager.GetString("valDeliveryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo dodávky musí byt vyplněno..
        /// </summary>
        public static string valDeliveryNumerRequired {
            get {
                return ResourceManager.GetString("valDeliveryNumerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail musí mít platný format např. (jmeno@provider.com).
        /// </summary>
        public static string valEmailAddressCorect {
            get {
                return ResourceManager.GetString("valEmailAddressCorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail musí být vyplněn..
        /// </summary>
        public static string valEmailRequired {
            get {
                return ResourceManager.GetString("valEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC musí být vyplněno..
        /// </summary>
        public static string valIcoRequired {
            get {
                return ResourceManager.GetString("valIcoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno musí být vyplněno..
        /// </summary>
        public static string valNameRequired {
            get {
                return ResourceManager.GetString("valNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum objednávky musí byt vyplněno..
        /// </summary>
        public static string valOrderDateRequired {
            get {
                return ResourceManager.GetString("valOrderDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo objednávky musí byt vyplněno..
        /// </summary>
        public static string valOrderNumerRequired {
            get {
                return ResourceManager.GetString("valOrderNumerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesla se neschodují..
        /// </summary>
        public static string valPasswordNotMatch {
            get {
                return ResourceManager.GetString("valPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí být vyplněno..
        /// </summary>
        public static string valPasswordRequired {
            get {
                return ResourceManager.GetString("valPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí obsahovat nejméně jednu číslici..
        /// </summary>
        public static string valPasswordRequiresDigit {
            get {
                return ResourceManager.GetString("valPasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí obsahovat nejméně jedno malé písmeno..
        /// </summary>
        public static string valPasswordRequiresLower {
            get {
                return ResourceManager.GetString("valPasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí obsahovat nejméně jeden specialní znak..
        /// </summary>
        public static string valPasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("valPasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí obsahovat nejméně jedno velké písmeno..
        /// </summary>
        public static string valPasswordRequiresUpper {
            get {
                return ResourceManager.GetString("valPasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno produktu musí byt vyplněno..
        /// </summary>
        public static string valProductNameRequired {
            get {
                return ResourceManager.GetString("valProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvantita musí byt vyplněna..
        /// </summary>
        public static string valQuantityRequired {
            get {
                return ResourceManager.GetString("valQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena musí byt vyplněna..
        /// </summary>
        public static string valTotalPriceRequired {
            get {
                return ResourceManager.GetString("valTotalPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena za jednotnku musí byt vyplněna..
        /// </summary>
        public static string valUnitPriceRequired {
            get {
                return ResourceManager.GetString("valUnitPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT musí být vyplněn..
        /// </summary>
        public static string valVatRequired {
            get {
                return ResourceManager.GetString("valVatRequired", resourceCulture);
            }
        }
    }
}
