//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFZ.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFZ.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        public static string valAction {
            get {
                return ResourceManager.GetString("valAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string valAddress {
            get {
                return ResourceManager.GetString("valAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celá objednávka.
        /// </summary>
        public static string valAllOrde {
            get {
                return ResourceManager.GetString("valAllOrde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo orientační.
        /// </summary>
        public static string valAlternativeStreetNumber {
            get {
                return ResourceManager.GetString("valAlternativeStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přílohy.
        /// </summary>
        public static string valAttachment {
            get {
                return ResourceManager.GetString("valAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scany priloh.
        /// </summary>
        public static string valAttachmentScanFiles {
            get {
                return ResourceManager.GetString("valAttachmentScanFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte přílohu.
        /// </summary>
        public static string valChooseFileAttachment {
            get {
                return ResourceManager.GetString("valChooseFileAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        public static string valCity {
            get {
                return ResourceManager.GetString("valCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        public static string valClose {
            get {
                return ResourceManager.GetString("valClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string valCompany {
            get {
                return ResourceManager.GetString("valCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa firmy.
        /// </summary>
        public static string valCompanyManagement {
            get {
                return ResourceManager.GetString("valCompanyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompletace.
        /// </summary>
        public static string valCompletation {
            get {
                return ResourceManager.GetString("valCompletation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompletace.
        /// </summary>
        public static string valCompletionJob {
            get {
                return ResourceManager.GetString("valCompletionJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdtě heslo.
        /// </summary>
        public static string valConfirmPassword {
            get {
                return ResourceManager.GetString("valConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazník.
        /// </summary>
        public static string valCustomer {
            get {
                return ResourceManager.GetString("valCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení zákazníka.
        /// </summary>
        public static string valCustomerManage {
            get {
                return ResourceManager.GetString("valCustomerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa zákazníků.
        /// </summary>
        public static string valCustomerManagement {
            get {
                return ResourceManager.GetString("valCustomerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum a čas.
        /// </summary>
        public static string valDateTime {
            get {
                return ResourceManager.GetString("valDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string valDelete {
            get {
                return ResourceManager.GetString("valDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doručeno.
        /// </summary>
        public static string valDelivered {
            get {
                return ResourceManager.GetString("valDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodávky.
        /// </summary>
        public static string valDelivery {
            get {
                return ResourceManager.GetString("valDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodat vše.
        /// </summary>
        public static string valDeliveryAll {
            get {
                return ResourceManager.GetString("valDeliveryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum dodávky.
        /// </summary>
        public static string valDeliveryDate {
            get {
                return ResourceManager.GetString("valDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo dodávky.
        /// </summary>
        public static string valDeliveryNumber {
            get {
                return ResourceManager.GetString("valDeliveryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číselníky.
        /// </summary>
        public static string valDial {
            get {
                return ResourceManager.GetString("valDial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIC.
        /// </summary>
        public static string valDIC {
            get {
                return ResourceManager.GetString("valDIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleva.
        /// </summary>
        public static string valDiscount {
            get {
                return ResourceManager.GetString("valDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string valEdit {
            get {
                return ResourceManager.GetString("valEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string valEmail {
            get {
                return ResourceManager.GetString("valEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybove hlášení.
        /// </summary>
        public static string ValErrorMessage {
            get {
                return ResourceManager.GetString("ValErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string valFailed {
            get {
                return ResourceManager.GetString("valFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor.
        /// </summary>
        public static string valFile {
            get {
                return ResourceManager.GetString("valFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název souboru.
        /// </summary>
        public static string valFileName {
            get {
                return ResourceManager.GetString("valFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ souboru.
        /// </summary>
        public static string valFileType {
            get {
                return ResourceManager.GetString("valFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string valFirstName {
            get {
                return ResourceManager.GetString("valFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomněli jste heslo?.
        /// </summary>
        public static string valForogotPassword {
            get {
                return ResourceManager.GetString("valForogotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domu.
        /// </summary>
        public static string valHome {
            get {
                return ResourceManager.GetString("valHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC.
        /// </summary>
        public static string valIco {
            get {
                return ResourceManager.GetString("valIco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vnořená chyba.
        /// </summary>
        public static string valInnerError {
            get {
                return ResourceManager.GetString("valInnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum fakturace.
        /// </summary>
        public static string valInvoiceDate {
            get {
                return ResourceManager.GetString("valInvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail faktury.
        /// </summary>
        public static string valInvoiceDetail {
            get {
                return ResourceManager.GetString("valInvoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura ke stazeni.
        /// </summary>
        public static string valInvoiceDonwload {
            get {
                return ResourceManager.GetString("valInvoiceDonwload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položky fakturace.
        /// </summary>
        public static string valInvoiceItems {
            get {
                return ResourceManager.GetString("valInvoiceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo faktury.
        /// </summary>
        public static string valInvoiceNumber {
            get {
                return ResourceManager.GetString("valInvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktury.
        /// </summary>
        public static string valInvoices {
            get {
                return ResourceManager.GetString("valInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena.
        /// </summary>
        public static string valItemsTotal {
            get {
                return ResourceManager.GetString("valItemsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editování jobu.
        /// </summary>
        public static string valJobEdit {
            get {
                return ResourceManager.GetString("valJobEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyklus jobu.
        /// </summary>
        public static string valJobLength {
            get {
                return ResourceManager.GetString("valJobLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joby.
        /// </summary>
        public static string valJobs {
            get {
                return ResourceManager.GetString("valJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pslední joby.
        /// </summary>
        public static string valJobScheduler {
            get {
                return ResourceManager.GetString("valJobScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa jobů.
        /// </summary>
        public static string valJobsManage {
            get {
                return ResourceManager.GetString("valJobsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa jobů.
        /// </summary>
        public static string valJobsManagement {
            get {
                return ResourceManager.GetString("valJobsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustit job.
        /// </summary>
        public static string valJobStart {
            get {
                return ResourceManager.GetString("valJobStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastavit job.
        /// </summary>
        public static string valJobStop {
            get {
                return ResourceManager.GetString("valJobStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum jobu.
        /// </summary>
        public static string valJobTime {
            get {
                return ResourceManager.GetString("valJobTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string valLastName {
            get {
                return ResourceManager.GetString("valLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední spuštění.
        /// </summary>
        public static string valLastStart {
            get {
                return ResourceManager.GetString("valLastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poslední status.
        /// </summary>
        public static string valLastStatus {
            get {
                return ResourceManager.GetString("valLastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka trvání.
        /// </summary>
        public static string valLength {
            get {
                return ResourceManager.GetString("valLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string valLog {
            get {
                return ResourceManager.GetString("valLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        public static string valLogin {
            get {
                return ResourceManager.GetString("valLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit.
        /// </summary>
        public static string valLoginBtn {
            get {
                return ResourceManager.GetString("valLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logy.
        /// </summary>
        public static string valLogMessage {
            get {
                return ResourceManager.GetString("valLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit.
        /// </summary>
        public static string valLogOut {
            get {
                return ResourceManager.GetString("valLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supstit manualně.
        /// </summary>
        public static string valManually {
            get {
                return ResourceManager.GetString("valManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        public static string valMobile {
            get {
                return ResourceManager.GetString("valMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string valName {
            get {
                return ResourceManager.GetString("valName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novy.
        /// </summary>
        public static string valNew {
            get {
                return ResourceManager.GetString("valNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová příloha.
        /// </summary>
        public static string valNewAttachment {
            get {
                return ResourceManager.GetString("valNewAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový zákazník.
        /// </summary>
        public static string valNewCustomer {
            get {
                return ResourceManager.GetString("valNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová dodávka.
        /// </summary>
        public static string valNewDelivery {
            get {
                return ResourceManager.GetString("valNewDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová objednávka.
        /// </summary>
        public static string valNewOrder {
            get {
                return ResourceManager.GetString("valNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat detail objednávky.
        /// </summary>
        public static string valNewOrderDetail {
            get {
                return ResourceManager.GetString("valNewOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový uživatel.
        /// </summary>
        public static string valNewUser {
            get {
                return ResourceManager.GetString("valNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávky.
        /// </summary>
        public static string valOrder {
            get {
                return ResourceManager.GetString("valOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum objednávky.
        /// </summary>
        public static string valOrderDate {
            get {
                return ResourceManager.GetString("valOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail objednávky.
        /// </summary>
        public static string valOrderDetail {
            get {
                return ResourceManager.GetString("valOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo objednavky.
        /// </summary>
        public static string valOrderNumber {
            get {
                return ResourceManager.GetString("valOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string valPassword {
            get {
                return ResourceManager.GetString("valPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo znovu.
        /// </summary>
        public static string valPasswordConfirm {
            get {
                return ResourceManager.GetString("valPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Část objednávky.
        /// </summary>
        public static string valPiceOfOrder {
            get {
                return ResourceManager.GetString("valPiceOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSC.
        /// </summary>
        public static string valPostalCode {
            get {
                return ResourceManager.GetString("valPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Společnost EFZ neuchovává v souvislosti s používáním nebo se stahováním dokumentů žádné osobní údaje., vyjma
        ///vašeho emailového účtu, který je povinný pro přístup na portál. Vaše osobní údaje jsou zpracovávány v souladu se
        ///zákonem č. 101/2000 Sb., o ochraně osobních údajů (dále jen „ZOOÚ“), v platném znění a s principy rámcových
        ///směrnic Evropské unie pro ochranu dat, zejména se směrnicí Evropského parlamentu a Rady 95/46/ES. Správcem a
        ///zároveň zpracovatelem těchto osobních údajů je společnost EFZ. Jakéko [rest of string was truncated]&quot;;.
        /// </summary>
        public static string valPrivacyContent {
            get {
                return ResourceManager.GetString("valPrivacyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zásady ochrany osobních údajů (Privacy Policy).
        /// </summary>
        public static string valPrivacyTitle {
            get {
                return ResourceManager.GetString("valPrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno produktu.
        /// </summary>
        public static string valProductName {
            get {
                return ResourceManager.GetString("valProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvantita.
        /// </summary>
        public static string ValQuantity {
            get {
                return ResourceManager.GetString("ValQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace.
        /// </summary>
        public static string valRegister {
            get {
                return ResourceManager.GetString("valRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat.
        /// </summary>
        public static string valRegisterBtn {
            get {
                return ResourceManager.GetString("valRegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamatovat si mě?.
        /// </summary>
        public static string valRememberMe {
            get {
                return ResourceManager.GetString("valRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string valRole {
            get {
                return ResourceManager.GetString("valRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustit manualně.
        /// </summary>
        public static string valRunJobManually {
            get {
                return ResourceManager.GetString("valRunJobManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string valSave {
            get {
                return ResourceManager.GetString("valSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace.
        /// </summary>
        public static string valSigIn {
            get {
                return ResourceManager.GetString("valSigIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spuštěn.
        /// </summary>
        public static string valStarted {
            get {
                return ResourceManager.GetString("valStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat.
        /// </summary>
        public static string valState {
            get {
                return ResourceManager.GetString("valState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string valStatus {
            get {
                return ResourceManager.GetString("valStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastaven.
        /// </summary>
        public static string valStoped {
            get {
                return ResourceManager.GetString("valStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        public static string valStreetName {
            get {
                return ResourceManager.GetString("valStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo popisne.
        /// </summary>
        public static string valStreetNumber {
            get {
                return ResourceManager.GetString("valStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V pořádku.
        /// </summary>
        public static string valSuccess {
            get {
                return ResourceManager.GetString("valSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPH.
        /// </summary>
        public static string valTaxRate {
            get {
                return ResourceManager.GetString("valTaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string valTelephone {
            get {
                return ResourceManager.GetString("valTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronická Fakturace Zákazníkem.
        /// </summary>
        public static string valTitle {
            get {
                return ResourceManager.GetString("valTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul.
        /// </summary>
        public static string valTitleAddress {
            get {
                return ResourceManager.GetString("valTitleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkova cena s DPH.
        /// </summary>
        public static string valTotalNet {
            get {
                return ResourceManager.GetString("valTotalNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena.
        /// </summary>
        public static string valTotalPrice {
            get {
                return ResourceManager.GetString("valTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPH celkem.
        /// </summary>
        public static string valTotalTax {
            get {
                return ResourceManager.GetString("valTotalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neautorizovaný přístup.
        /// </summary>
        public static string valUnautorizedAccess {
            get {
                return ResourceManager.GetString("valUnautorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednotková cena.
        /// </summary>
        public static string valUnitPrice {
            get {
                return ResourceManager.GetString("valUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrát.
        /// </summary>
        public static string valUpload {
            get {
                return ResourceManager.GetString("valUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení uživatele.
        /// </summary>
        public static string valUserManage {
            get {
                return ResourceManager.GetString("valUserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa uživatelů.
        /// </summary>
        public static string valUserManagemant {
            get {
                return ResourceManager.GetString("valUserManagemant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelé.
        /// </summary>
        public static string valUsers {
            get {
                return ResourceManager.GetString("valUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string valVat {
            get {
                return ResourceManager.GetString("valVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítejte v Portálu EFZ.
        /// </summary>
        public static string valWelcome {
            get {
                return ResourceManager.GetString("valWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení do Portálu provedete zadáním přihlašovacího jména a hesla do přihlašovacího okna po stisknutí
        ///tlačítka Přihlášení v pravém horním rohu..
        /// </summary>
        public static string valWelcomeP1 {
            get {
                return ResourceManager.GetString("valWelcomeP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud nemáte vytvořený účet, můžete si jej vytvořit po stisku tlačítka Registrace v pravém horním rohu.
        ///Následně vám správce portálu provede dodatečné nastavení, abyste mohli využívat všechny funkce portálu..
        /// </summary>
        public static string valWelcomeP2 {
            get {
                return ResourceManager.GetString("valWelcomeP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budete-li mít problémy s používáním Portálu EFZ, dejte nám, prosím, vědět na adresu helpdesk@efz.cz..
        /// </summary>
        public static string valWelcomeP3 {
            get {
                return ResourceManager.GetString("valWelcomeP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml soubory.
        /// </summary>
        public static string valXmlFiles {
            get {
                return ResourceManager.GetString("valXmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpracování XML.
        /// </summary>
        public static string valXmlProcessing {
            get {
                return ResourceManager.GetString("valXmlProcessing", resourceCulture);
            }
        }
    }
}
