//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFZ.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFZ.Resources.LabelsMessages", typeof(LabelsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=MsoNormal&gt;&lt;span style=&apos;font-family:Calibri, Arial, Helvetica, sans-serif&apos;&gt;Vážený zákazníku, &lt;br&gt;&lt;o:p&gt;&lt;/o:p&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p class=MsoNormal&gt;&lt;span style=&apos;font-family:Calibri, Arial, Helvetica, sans-serif&apos;&gt;byla zkompletována nová faktrura: {0}&lt;br&gt;&lt;o:p&gt;&lt;/o:p&gt;&lt;/span&gt;&lt;/p&gt;
        ///
        ///&lt;p class=MsoNormal&gt;&lt;span style=&apos;font-family:Calibri, Arial, Helvetica, sans-serif&apos;&gt;V odkaze níže naleznete novou fakturu:&lt;br&gt;&lt;o:p&gt;&lt;/o:p&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;a href=&quot;{1}&quot; style=&quot;margin: 0px; font-family: Calibri, Arial, Helvetica, sans-serif [rest of string was truncated]&quot;;.
        /// </summary>
        public static string valCompletationContent {
            get {
                return ResourceManager.GetString("valCompletationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://efz.azurewebsites.net/Completion/Customer?completionId={0}.
        /// </summary>
        public static string valCompletionUrl {
            get {
                return ResourceManager.GetString("valCompletionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFZ - Nová faktura.
        /// </summary>
        public static string valCompletionUrlName {
            get {
                return ResourceManager.GetString("valCompletionUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte zákazníka.
        /// </summary>
        public static string valCustomerSelect {
            get {
                return ResourceManager.GetString("valCustomerSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat přílohu?.
        /// </summary>
        public static string valDeleteAttachment {
            get {
                return ResourceManager.GetString("valDeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat zákazníka?.
        /// </summary>
        public static string valDeleteCustomer {
            get {
                return ResourceManager.GetString("valDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat uživatele?.
        /// </summary>
        public static string valDeleteUser {
            get {
                return ResourceManager.GetString("valDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte dodávku.
        /// </summary>
        public static string valDeliverySelect {
            get {
                return ResourceManager.GetString("valDeliverySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string valEmail {
            get {
                return ResourceManager.GetString("valEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jmeno.
        /// </summary>
        public static string valName {
            get {
                return ResourceManager.GetString("valName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte objednávku.
        /// </summary>
        public static string valOrderSelect {
            get {
                return ResourceManager.GetString("valOrderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string valPassword {
            get {
                return ResourceManager.GetString("valPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte roli.
        /// </summary>
        public static string valRoleSelect {
            get {
                return ResourceManager.GetString("valRoleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte uživatele.
        /// </summary>
        public static string valUserSelect {
            get {
                return ResourceManager.GetString("valUserSelect", resourceCulture);
            }
        }
    }
}
